# netlify.toml (Place this file in the ROOT of your repository)

[build]
  # These should match your Netlify UI settings
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  # Optional: Specify base directory if needed, but usually not required with the cd command
  # base = "frontend" # Usually not needed if using `cd frontend && ...` in the command

# The crucial redirect rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200